# Multiclass Classification Example

In this notebook, we will go over how to mimic a scikit learn model that performs multiclass classification using the `aisquared` library.

In [15]:
# import all required packages
from aisquared import utils
from sklearn.tree import DecisionTreeClassifier
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.preprocessing import MinMaxScaler
import numpy as np

In [16]:
# Load the data and split into training and testing sets
data = load_iris()['data']
labels = load_iris()['target']

x_train, x_test, y_train, y_test = train_test_split(data, labels)

scaler = MinMaxScaler().fit(x_train)
x_train = scaler.transform(x_train)
x_test = scaler.transform(x_test)

In [17]:
# Train the scikit-learn classifier
clf = DecisionTreeClassifier(max_depth = 4).fit(x_train, y_train)

In [18]:
# Create the neural network to train with
nnet = utils.get_model('fc', x_train.shape[-1], np.unique(y_train).shape[0], output_activation = 'softmax', size = 'medium')

In [19]:
# Use the mimic_model function to train the neural network to replicate the original model's performance
nnet = utils.mimic_model(
clf,
nnet,
x_train,
x_test,
y_test,
'classification',
'mse',
'accuracy',
'adam',
mimic_proba = True
)

Epoch 1/100
1/4 [======>.......................] - ETA: 1s - loss: 0.2211 - accuracy: 0.2812Performance measure set to accuracy
Model performance has not reached pruning threshold for 1 epoch(s)
4/4 [==============================] - 0s 2ms/step - loss: 0.2167 - accuracy: 0.5804
Epoch 2/100
4/4 [==============================] - 0s 2ms/step - loss: 0.2013 - accuracy: 0.7054
Epoch 3/100
4/4 [==============================] - 0s 1ms/step - loss: 0.1759 - accuracy: 0.7054
Epoch 4/100
4/4 [==============================] - 0s 1ms/step - loss: 0.1518 - accuracy: 0.7054
Epoch 5/100
4/4 [==============================] - 0s 1ms/step - loss: 0.1230 - accuracy: 0.7054
Epoch 6/100
4/4 [==============================] - 0s 1ms/step - loss: 0.0959 - accuracy: 0.7054
Epoch 7/100
4/4 [==============================] - 0s 1ms/step - loss: 0.0802 - accuracy: 0.8304
Epoch 8/100
4/4 [==============================] - 0s 1ms/step - loss: 0.0680 - accuracy: 0.8839
Epoch 9/100
4/4 [========================

In [20]:
# Get the predictions on test data from the original classifier and the neural network
clf_preds = clf.predict(x_test)
nnet_preds = nnet.predict(x_test).argmax(axis = 1)

2/2 [==============================] - 0s 843us/step


In [21]:
# Present the confusion matrices for both models

print('Performance on test data for original model:')
print(confusion_matrix(y_test, clf_preds))

print('\n\n')

print('Performance on test data for neural network:')
print(confusion_matrix(y_test, nnet_preds))

Performance on test data for original model:
[[11  0  0]
 [ 0 16  1]
 [ 0  0 10]]



Performance on test data for neural network:
[[11  0  0]
 [ 0 16  1]
 [ 0  0 10]]
