# Multiclass Classification Example

In this notebook, we will go over how to mimic a scikit learn model that performs multiclass classification using the `aisquared` library.

In [1]:
# import all required packages
from aisquared import utils
from sklearn.tree import DecisionTreeClassifier
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.preprocessing import MinMaxScaler
import numpy as np

In [2]:
# Load the data and split into training and testing sets
data = load_iris()['data']
labels = load_iris()['target']

x_train, x_test, y_train, y_test = train_test_split(data, labels)

scaler = MinMaxScaler().fit(x_train)
x_train = scaler.transform(x_train)
x_test = scaler.transform(x_test)

In [3]:
# Train the scikit-learn classifier
clf = DecisionTreeClassifier(max_depth = 4).fit(x_train, y_train)

In [4]:
# Create the neural network to train with
nnet = utils.get_model('fc', x_train.shape[-1], np.unique(y_train).shape[0], output_activation = 'softmax', size = 'medium')

In [5]:
# Use the mimic_model function to train the neural network to replicate the original model's performance
nnet = utils.mimic_model(
clf,
nnet,
x_train,
x_test,
y_test,
'classification',
'mse',
'accuracy',
'adam',
mimic_proba = True
)

Epoch 1/100


2023-01-05 14:31:07.367719: W tensorflow/core/platform/profile_utils/cpu_utils.cc:128] Failed to get CPU frequency: 0 Hz


1/4 [======>.......................] - ETA: 0s - loss: 0.2227 - accuracy: 0.0938Performance measure set to accuracy
Model performance has not reached pruning threshold for 1 epoch(s)
4/4 [==============================] - 0s 1ms/step - loss: 0.2158 - accuracy: 0.4107
Epoch 2/100
4/4 [==============================] - 0s 1ms/step - loss: 0.2039 - accuracy: 0.6250
Epoch 3/100
4/4 [==============================] - 0s 1ms/step - loss: 0.1861 - accuracy: 0.6607
Epoch 4/100
4/4 [==============================] - 0s 1ms/step - loss: 0.1653 - accuracy: 0.6607
Epoch 5/100
4/4 [==============================] - 0s 1ms/step - loss: 0.1450 - accuracy: 0.6607
Epoch 6/100
4/4 [==============================] - 0s 1ms/step - loss: 0.1134 - accuracy: 0.6607
Epoch 7/100
4/4 [==============================] - 0s 1ms/step - loss: 0.0959 - accuracy: 0.8839
Epoch 8/100
4/4 [==============================] - 0s 1ms/step - loss: 0.1028 - accuracy: 0.6607
Epoch 9/100
4/4 [==============================] - 0s

In [6]:
# Get the predictions on test data from the original classifier and the neural network
clf_preds = clf.predict(x_test)
nnet_preds = nnet.predict(x_test).argmax(axis = 1)

2/2 [==============================] - 0s 1ms/step


In [7]:
# Present the confusion matrices for both models

print('Performance on test data for original model:')
print(confusion_matrix(y_test, clf_preds))

print('\n\n')

print('Performance on test data for neural network:')
print(confusion_matrix(y_test, nnet_preds))

Performance on test data for original model:
[[13  0  0]
 [ 0 12  1]
 [ 0  0 12]]



Performance on test data for neural network:
[[13  0  0]
 [ 0 11  2]
 [ 0  0 12]]
